name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  corvus_macos:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.4_beta.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery --sanitize=thread
